spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_management
    username: postgres
    password: 102030
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false